### ISSUE TITLE
Generated Image cannot be found.

### ISSUE THREAD

**Issue by boudhayan-dev** [mixn/carbon-now-cli#10]
I used the following to generate the image: 
`carbon-now test.html`

The following error resulted:

```
D:\test>carbon-now test.html
 √ Processing test.html
 √ Preparing connection
 ↓ Opening in browser [skipped]
 √ Fetching beautiful image

  Done!

  The file can be found here: D:\test/carbon.png 😌

  Error: Sending code to https://carbon.now.sh went wrong.

  This is mostly due to:

  – Insensical input like `--start 10 --end 2`
  – Carbon being down or taking too long to respond
  – Your internet connection not working or being too slow
```

The generated Image isn't available in the given path.

**Comment by mixn** [comment]
Thanks for reporting! :) 

Hm, not sure cause I haven’t had the chance to test this on a Windows machine yet (or debug for that matter). It’s tested and works on macOS and Linux.

Interesting how it gives both the positive and negative feedback though.

Could you fork the repo and try commenting this https://github.com/mixn/carbon-now-cli/blob/master/cli.js#L151-L157 out? Then run `npm install` inside the repo and to install the dependencies and `node cli.js test/test-dummies/_index.html`.

**Comment by boudhayan-dev** [comment]
Okay so it worked the first time. A `carbon.png` file containing the snapshot of `_index.html` was created. But on subsequent try's, it did not produce any result.

```
C:\Users\Boudhayan Dev\Desktop\carbon-now-cli>node cli.js test/test-dummies/_index.html
 √ Processing test/test-dummies/_index.html
 √ Preparing connection
 ↓ Opening in browser [skipped]
 √ Fetching beautiful image

  Done!

  The file can be found here: C:\Users\Boudhayan Dev\Desktop\carbon-now-cli/carbon.png 😌
```

I did a fresh build in different directory but this time it did not even work for the first time. However, success message was displayed as above.

**Comment by rafal-olszewski** [comment]
The same happens on Mac

```
➜  ~ carbon-now -i ~/dev/app/src/js/main.js
? Syntax theme: Twilight
? Window theme: None
? Font family: Fira Code
? Font size: 24
? Include window controls? Yes
? Include line numbers? No
? Auto adjust width? No
? Vertical padding 20px
? Horizontal padding 20px
? Include drop shadow? No
? Make squared image? No
? Add Carbon watermark? No
? Export size 2x
? Export as… png
 ✔ Processing /Users/rafal/dev/app/src/js/main.js
 ✔ Preparing connection
 ↓ Opening in browser [skipped]
 ✔ Fetching beautiful image

  Done!

  The file can be found here: /Users/rafal/carbon.png 😌

  Error: Sending code to https://carbon.now.sh went wrong.

  This is mostly due to:

  – Insensical input like `--start 10 --end 2`
  – Carbon being down or taking too long to respond
  – Your internet connection not working or being too slow
```

**Comment by mixn** [comment]
@boudhayan-dev @rafal-olszewski Could you try the steps provided here https://github.com/mixn/carbon-now-cli/issues/9#issuecomment-404339159 and report back? Thanks!

**Comment by boudhayan-dev** [comment]
No luck. Both the messages are being displayed again.

```
D:\carbon-now-cli>node cli.js test/test-dummies/_index.html
 √ Processing test/test-dummies/_index.html
 √ Preparing connection
 √ Processing test/test-dummies/_index.html
 √ Preparing connection
 ↓ Opening in browser [skipped]
 √ Fetching beautiful image

  Done!

  The file can be found here: D:\carbon-now-cli/carbon.png 😌

  Error: Sending code to https://carbon.now.sh went wrong.

  This is mostly due to:

  – Insensical input like `--start 10 --end 2`
  – Carbon being down or taking too long to respond
  – Your internet connection not working or being too slow

  Additional information:

  TypeError: Cannot read property 'match' of undefined
```

**Comment by mixn** [comment]
@boudhayan-dev Thanks for reporting back. :) Hm… have you tried a custom location? Didn’t work either? Like `carbon-now foo.js -l ~/Somelocation`.

**Comment by boudhayan-dev** [comment]
**@mixn**  Unfortunately it did not work this time as well. I did a clean install and even commented out `L151-157` before `npm install` , yet no luck.

**Installation -**

```
D:\carbon-now-cli>git checkout bug/9
Already on 'bug/9'
Your branch is up to date with 'origin/bug/9'.

D:\carbon-now-cli>npm install

> puppeteer@1.5.0 install D:\carbon-now-cli\node_modules\puppeteer
> node install.js

Downloading Chromium r564778 - 125.2 Mb [====================] 100% 0.0s
Chromium downloaded to D:\carbon-now-cli\node_modules\puppeteer\.local-chromium\win64-564778
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 831 packages in 113.285s

```

**Test -**

```
D:\carbon-now-cli>node cli.js test.html -l D:\carbon-now-cli
 √ Processing test.html
 √ Preparing connection
 ↓ Opening in browser [skipped]
 √ Fetching beautiful image

  Done!

  The file can be found here: D:\carbon-now-cli/carbon.png 😌
```
 
You can see the directory listing as well as the chromium response in the `test.html` file.

![output](https://user-images.githubusercontent.com/20648536/42649397-3c2c0f78-8627-11e8-8d31-e6a249b4a378.JPG)
![output2](https://user-images.githubusercontent.com/20648536/42649403-40ee1cc2-8627-11e8-9b32-f864e2d9073c.JPG)

**Comment by mixn** [comment]
Have you tried saving to any other place than `D:` via `-l`?

Also, check and try https://github.com/mixn/carbon-now-cli/issues/9#issuecomment-404693397, maybe that will help. It adds an extra flag to the headless Chrome via `-S`.

@rafal-olszewski Maybe you could try this, too. :)

**Comment by boudhayan-dev** [comment]
@mixn  I have tried both the suggestions. Did not work.

**Comment by mittalyashu** [comment]
Facing the same problem.

![image](https://user-images.githubusercontent.com/29014463/42690080-a88df2be-86c0-11e8-8762-127bcab16bf0.png)

**Comment by Sneezoo** [comment]
I suspect `Page.downloadBehavior` to be the problem, but I can't prove it with tests so I just wrote a hacky workaround for you guys.
You can clone my fork https://github.com/Sneezoo/carbon-now-cli and checkout `downloadBehavior-workaround`:
```bash
git clone https://github.com/Sneezoo/carbon-now-cli.git
git checkout downloadBehavior-workaround
```
@boudhayan-dev @mittalyashu @rafal-olszewski Could you please try again with my changes and report back?

**Comment by boudhayan-dev** [comment]
@Sneezoo  I did a ` npm i -g carbon-now-cli` with your suggested edits. It did not work when the tool is installed globally.However, when it was installed locally, it works with `node cli.js filename.ext`.  Is it supposed to be like this ?

**Comment by mittalyashu** [comment]
I hope I did correctly:

Here is the log file I got: [2018-07-14T07_01_00_855Z-debug.log](https://github.com/mixn/carbon-now-cli/files/2194746/2018-07-14T07_01_00_855Z-debug.log)

![image](https://user-images.githubusercontent.com/29014463/42722039-ac4db4a0-8762-11e8-82d3-6813f39e59ba.png)

**Comment by Sneezoo** [comment]
Hi! I hope my instructions haven't been too unclear. My fix is not merged to carbon-now-cli, yet. Also I will have to invest more time on it, to make it stable and enable features like SVG and selecting a target directory.
This time the complete instructions, to try the workaround:
```bash
git clone https://github.com/Sneezoo/carbon-now-cli.git
cd carbon-now-cli
git checkout downloadBehavior-workaround
npm install
node cli.js awesome-code.html # i also had to add '-S' so you may try that, too
```

**Comment by mixn** [comment]
@boudhayan-dev @mittalyashu You have to try it locally (**not** via the global that comes via `npm i -g carbon-now-cli`), since it’s a fork. :)
