### ISSUE TITLE
Typescript can't render color

### ISSUE THREAD

**Issue by BigGress** [mixn/carbon-now-cli#11]
Please check this code.

https://carbon.now.sh/?bg=rgba(0,0,0,0)&t=duotone-dark&wt=none&l=typescript&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=48px&ph=32px&ln=false&fm=Hack&fs=13px&lh=133%25&si=false&code=class%2520OlapTable%2520extends%2520TableCtrl%2520%257B%250A%2520%2520constructor(public%2520config%253A%2520any)%2520%257B%250A%2520%2520%2520%2520super(config)%253B%250A%2520%2520%257D%250A%250A%2520%2520%252F**%250A%2520%2520%2520*%2520%25E8%25BF%2599%25E4%25B8%25AA%25E6%2596%25B9%25E6%25B3%2595%25E5%258F%25AA%25E6%2598%25AF%25E5%258D%258F%25E5%258A%25A9%25E5%258F%2591%25E5%25B0%2584%25E8%25B0%2583%25E7%2594%25A8dataBack%250A%2520%2520%2520*%252F%250A%2520%2520public%2520resHandle(res)%2520%257B%250A%2520%2520%2520%2520%252F%252F%2520sql%252Folap%2520%25E8%258E%25B7%25E5%258F%2596%25E5%259B%259E%25E6%259D%25A5%25E7%259A%2584%25E6%2595%25B0%25E6%258D%25AE%25E6%25A0%25BC%25E5%25BC%258F%25E4%25B8%258D%25E4%25B8%2580%25E6%25A0%25B7%250A%2520%2520%2520%2520if%2520(this.config.mode)%2520%257B%250A%2520%2520%2520%2520%2520%2520this.data%2520%253D%2520res.data.data%253B%250A%2520%2520%2520%2520%257D%2520else%2520%257B%250A%2520%2520%2520%2520%2520%2520this.data%2520%253D%2520res.data%253B%250A%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520this.pageObj.total%2520%253D%2520res.total%253B%250A%2520%2520%2520%2520this.config.dataBack(res.data)%253B%250A%250A%2520%2520%2520%2520this.calculateExtend()%253B%250A%2520%2520%257D%250A%250A%2520%2520public%2520errHandle(res)%2520%257B%250A%2520%2520%2520%2520return%2520this.config.errBack(res)%253B%250A%2520%2520%257D%250A%250A%2520%2520%252F%252F%2520%25E5%25A4%2584%25E7%2590%2586table%25E5%258D%2595%25E5%2585%2583%25E6%25A0%25BC%25E6%2598%25BE%25E7%25A4%25BA%25E6%2597%25B6%25E9%259C%2580%25E8%25A6%2581%252C%2520%25E5%258D%2583%25E5%2588%2586%25E4%25BD%258D%25E5%2595%25A5%25E7%259A%2584%25E5%2586%2585%25E5%25AE%25B9%250A%2520%2520public%2520renderCell(text%253A%2520string%252C%2520keyname%253A%2520string)%2520%257B%250A%2520%2520%2520%2520return%2520handleCellText(text%252C%2520findSourceData(keyname%252C%2520queryConfig%252C%2520%27theIndex%27))%253B%250A%2520%2520%257D%250A%257D&es=2x&wm=false

**Comment by Keraito** [comment]
@BigGress the problem seems to be in the language set in your url. Now it's `l=typescript`, but it should be `l=application/typescript`.

**Comment by mixn** [comment]
@Keraito Seems like @Keraito is right about this.

As I assumed, carbon-now-cli handles this [correctly](https://github.com/mixn/carbon-now-cli/blob/master/src/helpers/language-map.json#L112-L113) — and so does Carbon itself. 

Are you setting this manually?
