### ISSUE TITLE
Just a question really

### ISSUE THREAD

**Issue by okonomiyaki3000** [mixn/carbon-now-cli#13]
What font is that with the cool 'f'? The one in the example that starts like `const unfold =`

**Comment by mixn** [comment]
Hi. :) I use `const unfold =` all over the place in the docs, haha. Where exactly?

**Comment by okonomiyaki3000** [comment]
In the readme at the top of this repo. The rendered image is using a font that might be italicized and the 'f' has a little hook at the bottom. I thought I was familiar with most of the common monospaced fonts but I haven't seen this before.

**Comment by okonomiyaki3000** [comment]
The example claims IBM Plex Mono but I don't think it is.

**Comment by okonomiyaki3000** [comment]
Ah! Sorry, I was wrong. It is IBM Plex Mono italic. I didn't realize its italic version was so different from regular. It's pretty cool though.

**Comment by mixn** [comment]
Glad you like it. :) I’ve been using the regular, extra light version for several months now in both terminal & editor. I really like.

Thanks for closing, too! :)
