### ISSUE TITLE
Add options for styling text as you can do on the website

### ISSUE THREAD

**Issue by BoKKeR** [mixn/carbon-now-cli#141]
**Is your feature request related to a problem? Please describe.**
Currently you can generate these images from the website (bold text, blue text), but there is no way of doing this with the cli 
![carbon (7)](https://github.com/mixn/carbon-now-cli/assets/2664857/6d3af5b1-a1be-4667-80cf-ffe5ebc65d46)

**Describe the solution you’d like:**
Have a markdown option for coloring and styling text

**Additional context:**
No other context

**Comment by mixn** [comment]
Hey @BoKKeR, thanks for opening. 🙂 

This definitely sounds useful. Could you elaborate a bit on what an ideal implementation would look like in your opinion?

I’ve only very quickly played around with this feature on the Carbon website just now and noticed that the state of these things is neither represented in the query string, nor in `localStorage` or anywhere else. Re-loading leads to losing all changes.

Plus, the edits seem to solely be able to be performed via mouse interactions, e.g. highlighting and then confirming in the UI. This particularly sounds like a nightmare to implement via the CLI.

Am I missing something here?

Thanks.

**Comment by BoKKeR** [comment]
Yes you are right, I was under the impression that you are the author of the site. Considering that the naming is the same and the branding. 

Original repo would have to implement those features. 

I also wonder if the original owners approve of this project. Since it is using their API/service.

**Comment by mixn** [comment]
@BoKKeR 

The repo for the Carbon website and web app can be found [here](https://github.com/carbon-app/carbon), I’m not the original owner of it, I only own this Carbon-related project.

And yes, they [approve of it](https://github.com/carbon-app/carbon#tools). 🙂😉

What did you mean by “_as you can do on the website_”, in the issue title? As you mentioned, the website can already do these things.
