### ISSUE TITLE
Setting to adjust the orientation of the generated image for vertical images

### ISSUE THREAD

**Issue by JavierReyes945** [mixn/carbon-now-cli#168]
I know it might seem like an unnecessary request. I have been generating images with this tool as the text rendering is very good. I use the generated images for presentations and stuff, but recently I wanted to use those images as wallpapers on some of my machines. It looks really nice.

Only problem is, I have vertical monitors, and I wanted to be able to set up the tool in some way that allow to generate images with a vertical aspect ratio, or that the code generated is placed with a 90° rotation, so that the image can be rotated and used on devices with vertical screens (rotated monitors, smartphones, even traditional documents with vertical orientation).

Would this be possible under current state? Would this be a setting implementation, or an extra function/feature?

Thanks for this tool, BTW!

**Comment by mixn** [comment]
Hey @JavierReyes945, thanks for opening. Been quite swamped since the beginning of the year, but I will tackle a new release of the CLI soon and, amongst other things, address this (somehow.) 🙂 Thanks for your patience, appreciated!

**Comment by mixn** [comment]
Hey @JavierReyes945, sorry for the big delay, finally getting around to shipping #276. 🙂 

I assume this is not something the web app (https://carbon.now.sh) covers, right? 

If not, I most likely won‘t tackle this since it’s fairly out of scope of the CLI. If the web app supports it, I’ll gladly add it! 🙂

**Comment by mixn** [comment]
I just spent some time looking and can’t find this feature in the web app + it’s easily achievable with OS-native functionalities (or something like `https://github.com/vseventer/sharp-cli`, so this is out of scope for `carbon-now-cli` itself. 😊
