### ISSUE TITLE
Support setting image title

### ISSUE THREAD

**Issue by jloewe** [mixn/carbon-now-cli#206]
**Is your feature request related to a problem? Please describe.**
When you open carbon, you can specify an image title which is included in the screenshot (have a look at the example).

![Example](https://github.com/mixn/carbon-now-cli/assets/11992962/5f79b70c-010b-417b-92d6-eec7fe1ec7c4)
[Carbon URL](https://carbon.now.sh/?bg=rgba%28171%2C184%2C195%2C0%29&t=seti&wt=none&l=auto&width=559&ds=false&dsyoff=20px&dsblur=68px&wc=true&wa=false&pv=0px&ph=0px&ln=true&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=4x&wm=false&code=%252F%252F%2520Example%2520from%2520https%253A%252F%252Fcarbon.now.sh%252F%250Aconst%2520unfold%2520%253D%2520%28f%252C%2520seed%29%2520%253D%253E%2520%257B%250A%2520%2520const%2520go%2520%253D%2520%28f%252C%2520seed%252C%2520acc%29%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520const%2520res%2520%253D%2520f%28seed%29%250A%2520%2520%2520%2520return%2520res%2520%253F%2520go%28f%252C%2520res%255B1%255D%252C%2520acc.concat%28%255Bres%255B0%255D%255D%29%29%2520%253A%2520acc%250A%2520%2520%257D%250A%2520%2520return%2520go%28f%252C%2520seed%252C%2520%255B%255D%29%250A%257D&tb=_unfold.js)

**Describe the solution you’d like:**
- automatically set the title when a file is used
- flag to manually specify the title

**Describe alternatives you’ve considered:**
- leaving the title out, which is not favorable when you have multiple screenshots next to each other

**Additional context:**
You can specify the image title using the `tb` query parameter.

**Comment by mixn** [comment]
Hey @jloewe, thanks for opening! :) I wasn’t aware this was a thing. I’ll try to make some time and add it asap, since it’s just another param, shouldn’t be too much work.

**Comment by jloewe** [comment]
> Hey @jloewe, thanks for opening! :) I wasn’t aware this was a thing. I’ll try to make some time and add it asap, since it’s just another param, shouldn’t be too much work.

Thank you in advance! Take your time. I took a look at it, but I'm not sure if I could submit a qualified PR.
It looks like part of your module api would have to be changed ([Prompt.getFile](https://github.com/mixn/carbon-now-cli/blob/master/cli.ts#L25) would need to return the file and the name if it is specified, or another getter for the file name could be added).
If you want, I can try to implement this, but I'm not sure if I would match your preferred style.

**Comment by mixn** [comment]
Been quite swamped since the beginning of the year, but I will tackle a new release of the CLI soon and, amongst other things, address this (somehow.) 🙂 Thanks for your patience, appreciated! @jloewe

**Comment by mixn** [comment]
Apologies that it took me so long to get to this. 😅 Once I started it was all straightforward and fast, I should have just started earlier. 😄 That being said, I just shipped [`v2.1`](https://github.com/mixn/carbon-now-cli/releases/tag/v2.1.0), which includes `titleBar` as a config option and automatically detects things, if `titleBar` is not provided. 🎉

### Example

Install the new `v2.1`:
```
npm install carbon-now-cli -g
```

Title is auto-detected if not provided:
```
carbon-now ./test/test-dummies/_unfold.js --to-clipboard
```
![image](https://github.com/user-attachments/assets/89fc2d85-a593-46da-b198-b4326c433a6d)

Overwrite title for this run via `titleBar` with the new `--settings` flag:

```
carbon-now ./test/test-dummies/_unfold.js --settings '{"titleBar":"custom-title"}' --to-clipboard
```
![image](https://github.com/user-attachments/assets/88e1f759-4798-4f70-82fc-70ace90ef9ea)

`titleBar` can also be put into a preset, if needed, just like any other option. 

Enjoy! @jloewe

**Comment by jloewe** [comment]
I've just tried it out and it works great! Thank you

**Comment by mixn** [comment]
@jloewe If only I shipped features as fast as I get feedback on them, haha. Thanks for the instant response; much appreciated! I’m glad it works and solves your problem. And thanks for opening + feedbacking. :)
