### ISSUE TITLE
`widthAdjustment: true` do not exceed 1024px

### ISSUE THREAD

**Issue by am29d** [mixn/carbon-now-cli#207]
**Describe the bug**
When I try to generate image with a long code line, the output image is fixed to 1024p for `1x` and 2048p for `2x` output size. 

**To Reproduce**

1. Run `carbon-now` with…
2. Wait for image to download…
3. See error
4. Paste code to carbon.now.sh using adjustWidth true
5. The image is in full width without line breaks

** Code I am using **

```typescript
import { BatchProcessor, EventType, processPartialResponse, } from '@aws-lambda-powertools/batch';
import type { SQSEvent, SQSRecord, Context, SQSBatchResponse } from 'aws-lambda';

const processor = new BatchProcessor(EventType.SQS);

const recordHandler = async (record: SQSRecord): Promise<void> => {
  const payload = record.body;
};

export const handler = async (
  event: SQSEvent,
  context: Context
): Promise<SQSBatchResponse> => {
  return processPartialResponse(event, recordHandler, processor, {context});
};
```

**Configuration json file for the cli**
```json
{
    "latest-preset": {
        "theme": "night-owl",
        "backgroundColor": "#161E2D",
        "dropShadows": false,
        "exportSize": "1x",
        "firstLineNumber": 1,
        "fontFamily": "Hack",
        "fontSize": "18px",
        "language": "auto",
        "lineHeight": "133%",
        "lineNumbers": true,
        "selectedLines": "*",
        "squaredImage": false,
        "type": "png",
        "watermark": false,
        "widthAdjustment": true,
        "windowControls": false,
        "windowTheme": "none"
    }
}
```

**Expected behavior**
I expect the tool to not break the line and take as much with as necessary 

**Screenshots**
Carbon website manually : 
<img width="1191" alt="Screenshot 2024-03-21 at 12 37 54" src="https://github.com/mixn/carbon-now-cli/assets/2674178/db7951dd-64cb-48f1-9bc5-78651c7b0772">

Output using cli
![batch-cmwtfGg40t](https://github.com/mixn/carbon-now-cli/assets/2674178/956c49e5-10f7-40e9-8136-5c8f821b6cdb)

Carbon website using `--open-in-browser` flag:

<img width="1810" alt="Screenshot 2024-03-21 at 12 42 32" src="https://github.com/mixn/carbon-now-cli/assets/2674178/af6feb42-f052-436c-91c7-976ca17ab8a4">

Edit: I tried to reduce the `fontSize` to 14 or 12, but the results are still ab bit weird, but the width seems to be correct:

![batch-X2QN56ETIo](https://github.com/mixn/carbon-now-cli/assets/2674178/eb5b54a1-9e8a-4173-b28d-4f5c35d1dbcf)

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: macOS
- `--engine` used [e.g. `chromium`, `firefox`, `webkit`]: all engines produce the same output
- Carbon URL (run with `--open-in-browser` to see) [e.g. carbon.now.sh?bg=pink]: https://carbon.now.sh/?bg=%23161E2D&code=import%2520%257B%2520BatchProcessor%252C%2520EventType%252C%2520processPartialResponse%252C%2520%257D%2520from%2520%27%2540aws-lambda-powertools%252Fbatch%27%253B%250Aimport%2520type%2520%257B%2520SQSEvent%252C%2520SQSRecord%252C%2520Context%252C%2520SQSBatchResponse%2520%257D%2520from%2520%27aws-lambda%27%253B%250A%250Aconst%2520processor%2520%253D%2520new%2520BatchProcessor%28EventType.SQS%29%253B%250A%250Aconst%2520recordHandler%2520%253D%2520async%2520%28record%253A%2520SQSRecord%29%253A%2520Promise%253Cvoid%253E%2520%253D%253E%2520%257B%250A%2520%2520const%2520payload%2520%253D%2520record.body%253B%250A%257D%253B%250A%250Aexport%2520const%2520handler%2520%253D%2520async%2520%28%250A%2520%2520event%253A%2520SQSEvent%252C%250A%2520%2520context%253A%2520Context%250A%29%253A%2520Promise%253CSQSBatchResponse%253E%2520%253D%253E%2520%257B%250A%2520%2520return%2520processPartialResponse%28event%252C%2520recordHandler%252C%2520processor%252C%2520%257Bcontext%257D%29%253B%250A%257D%253B&dropShadows=false&ds=false&dsblur=68px&dsyoff=20px&es=1x&fl=1&fm=Hack&fs=18px&l=auto&lh=133%25&ln=true&ph=32px&pv=48px&si=false&sl=%2A&t=night-owl&type=png&wa=true&wc=false&wm=false&wt=none

<details>
  <summary>Code snippet</summary>
  <pre>
  
  </pre>
</details>

**Comment by mixn** [comment]
Hey @EcoFreshKase, thanks for opening. Been quite swamped since the beginning of the year, but I will tackle a new release of the CLI soon and, amongst other things, address this. 🙂 Thanks for your patience, appreciated!

**Comment by thomergil** [comment]
Bump... :) I have the same problem. It seems odd that it introduces unnecessary line breaks.

**Comment by thomergil** [comment]
Turns out, `width` is an undocumented option for `carbon-now.json`. I only discovered it because I exported the config from carbon.now.sh. You should add this to the documentation.

**Comment by Tomas2D** [comment]
Any update on this?
