### ISSUE TITLE
Multi language version

### ISSUE THREAD

**Issue by prosimplecoding** [mixn/carbon-now-cli#21]
I suggest add function for multi language version.

**Comment by mixn** [comment]
Hi and thanks for reaching out. :) I am not entirely sure on what you mean — could you please elaborate a bit? @prosimplecoding

**Comment by prosimplecoding** [comment]
@mixn I suggested that carbon.now.sh be available in different languages. In addition, I meant the possibility that people from different countries will be able to add their language to the interface.

**Comment by mixn** [comment]
@prosimplecoding I only made the CLI, the repository for the web interface can be found [here](https://github.com/dawnlabs/carbon). :)
