### ISSUE TITLE
Carbon-now-cli@next is stuck installation at executeActions

### ISSUE THREAD

**Issue by mittalyashu** [mixn/carbon-now-cli#23]
Carbon-now-cli@next is stuck at installation `postinstall: sill install executeActions`

![image](https://user-images.githubusercontent.com/29014463/43988868-60b1046a-9d5c-11e8-9a3f-743bff686343.png)

**Comment by mixn** [comment]
Hi. :) Getting stuck in `postinstall` can often be due to a bad internet connection. Please run it with `--verbose` like so `npm i -g carbon-now-cli@next --verbose` and see how long it takes.

Also, what Node version are you using?

**Comment by mittalyashu** [comment]
Node version `10.8.0`

I have tried to install it many times but facing the same issue every time.

**Comment by mittalyashu** [comment]
https://gist.github.com/mittalyashu/5534d6174186e264b5fe8a572f41acd4

**Comment by mixn** [comment]
I tried it with `v10.8.0`, worked without problems for me. Also, **none** of the dependencies loaded from cache take more than `50ms` for me, which is much, much faster than yours. Those numbers are insane. 😮 

I researched this further related to Windows. You should try 

a) clearing the npm cache
b) doing

```
npm config set registry http://registry.npmjs.org/ --global
npm config set registry http://registry.npmjs.org/
```

That should help.

**Comment by mittalyashu** [comment]
> Also, are you behind a firewall of some sort?

Don't know 😂

**Comment by mittalyashu** [comment]
I think it works.

```
C:\Users\YASHU>npm i -g carbon-now-cli@next
C:\Users\YASHU\AppData\Roaming\npm\carbon-now -> C:\Users\YASHU\AppData\Roaming\npm\node_modules\carbon-now-cli\cli.js

> puppeteer@1.7.0 install C:\Users\YASHU\AppData\Roaming\npm\node_modules\carbon-now-cli\node_modules\puppeteer
> node install.js

Downloading Chromium r579032 - 127.7 Mb [====================] 100% 0.0s
Chromium downloaded to C:\Users\YASHU\AppData\Roaming\npm\node_modules\carbon-now-cli\node_modules\puppeteer\.local-chro
mium\win64-579032
+ carbon-now-cli@1.1.0-0
added 390 packages from 274 contributors in 264.163s
```

Let me see if it works.

**Comment by mittalyashu** [comment]
When I run this command `carbon-now` it showed me this error

![cmd_2018-08-11_23-36-52](https://user-images.githubusercontent.com/29014463/43994767-eff80430-9dbf-11e8-8e41-2b7ef8645c71.png)

Where it should be supposed to create this directory `.carbon-now.json`?

**Comment by mixn** [comment]
Happy it worked! :) I’ll close this issue then. :)

As the `Error` suggests, you have to provide at least a file, e.g.

```
carbon-now my-file.js
```

Thanks for the feedback, glad it got resolved. :)

**Comment by mittalyashu** [comment]
But it didn't ask me these two questions.

![image](https://user-images.githubusercontent.com/29014463/43994959-50bf6a44-9dc3-11e8-9123-b9e91edb931f.png)

**Comment by mixn** [comment]
@mittalyashu Which version are you using? Run `carbon-now --version` to find out.

**Comment by mittalyashu** [comment]
Carbon version: `1.0.4`

**Comment by mixn** [comment]
Well, as it [says in the docs](https://github.com/mixn/carbon-now-cli#disclaimer), presets can only currently only be used through `@next` aka. atm `v1.1.0-0`. 😉😄

**Comment by mittalyashu** [comment]
But I did used this command `npm i -g carbon-now-cli@next` to install.

**Comment by mixn** [comment]
@mittalyashu The version is definitely off though. Maybe uninstall `npm uninstall -g carbon-now-cli` and re-install `npm i -g carbon-now-cli@next`. Should work without problems.

**Comment by mittalyashu** [comment]
Still the same problem

![image](https://user-images.githubusercontent.com/29014463/43995668-ff023274-9dcf-11e8-9159-55eee9f02c7f.png)

**Comment by mittalyashu** [comment]
> That looks like some wonky Windows stuff that I don’t understand. 😅 It literally doesn’t do what it should. 

No worries ☺️. Thanks for the help anyways.

I will try to `run as administrator`.

**Comment by mittalyashu** [comment]
I have tested the same thing with some other npm package and that worked fine, but face the same issue with carbon again, even in the administrator mode.

![image](https://user-images.githubusercontent.com/29014463/43995969-e94ddc74-9dd6-11e8-9f38-313edfbc1483.png)

**Comment by mittalyashu** [comment]
@minx, check this thread https://twitter.com/mittalyashu77/status/1028360489351426052?s=19

**Comment by mittalyashu** [comment]
Hmm... So, should I wait until the release is out from `next`.

**Comment by mittalyashu** [comment]
Means I am on the next version, but is not showing it correctly. Right?

**Comment by mixn** [comment]
@mittalyashu No, it means that you have most likely multiple versions installed and the wrong one is being used by default.

**Comment by mittalyashu** [comment]
But I have even tried to remove it globally and then tried installing it again.

**Comment by mixn** [comment]
@mittalyashu As mentioned in the Twitter thread, you might have several versions installed and removing one globally, doesn’t remove the other.

**Comment by mittalyashu** [comment]
So, what should I do now?

**Comment by mittalyashu** [comment]
I made it work, and it has installed correctly now 🎉🥂🙌.

![image](https://user-images.githubusercontent.com/29014463/44231849-0f287280-a1bd-11e8-80b9-6d153d4d8467.png)
