### ISSUE TITLE
Update the npm version 

### ISSUE THREAD

**Issue by c-o-d-e-xx** [mixn/carbon-now-cli#275]
**Describe the bug**
Getting many bugs not even working 

**To Reproduce**

1. Run `carbon-now` with…
2. Wait for image to download…
3. See error

**Expected behavior**

**Screenshots**

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]:
- `--engine` used [e.g. `chromium`, `firefox`, `webkit`]:
- Carbon URL (run with `--open-in-browser` to see) [e.g. carbon.now.sh?bg=pink]:

<details>
  <summary>Code snippet</summary>
  <pre>
  
  </pre>
</details>

**Comment by mixn** [comment]
Apologies that it took me so long to get to this. 😅 I just shipped [`v2.1`](https://github.com/mixn/carbon-now-cli/releases/tag/v2.1.0), all works now + versions are all up to date, etc. 🎉 Enjoy!
