### ISSUE TITLE
Bug: Language setting is ignored

### ISSUE THREAD

**Issue by ad-si** [mixn/carbon-now-cli#32]
At https://github.com/mixn/carbon-now-cli/blob/master/src/helpers/default-settings.js#L7 there is a `"l"` field defined to change the language. However, it seems to be ignored.

**Comment by mixn** [comment]
The language is detected automatically based on [language-map.json](https://github.com/mixn/carbon-now-cli/blob/master/src/helpers/language-map.json). I should maybe add that as a comment to that file, thanks for pointing out.

**Comment by ad-si** [comment]
Ok, but Bash seems to be missing from the language-map, although carbon supports it:

![screen shot 2018-09-20 at 13 30 35](https://user-images.githubusercontent.com/36796532/45821724-731cea00-bcd9-11e8-9f15-6944181b02e8.png)

**Comment by ad-si** [comment]
Or actually not OK. When I use it like this `carbon-now (echo 'ls -la' | psub)`, the file doesn't have a file ending and therefore I should be able to specify the target language.
Also: You should probaly add support for stdin. E.g. `echo 'ls -la' | carbon-now`

**Comment by mixn** [comment]
> Ok, but Bash seems to be missing from the language-map, although carbon supports it:

True, I apparently missed that one. Will add for `.sh` extension. Files with shebangs and no extension will default to `auto` then. Thanks!

`auto` seems to not auto-detect Bash on Carbon’s website though. 🤔 See https://goo.gl/GRAK8b vs. https://goo.gl/UfxugR . I’ll check their issues later.

 

> Or actually not OK.

OR RLY? 😁



> You should probaly add support for stdin.

#12. This was already a feature that was done and implemented on `feature/12` and my brand new Macbook randomly died two weeks ago, so I lost all that work. 🙄 Probably should have pushed the branch, but, oh well. TL;DR: that will happen anyway. :)
