### ISSUE TITLE
Is it possible to use this program as a module in Node.js?

### ISSUE THREAD

**Issue by cawa-93** [mixn/carbon-now-cli#36]
I would like to add some logic, automatically set the settings depending on the file type and add post-processing after creating the image.

**Comment by mixn** [comment]
Hi @cawa-93.

While this tool is a CLI and intended to be used via terminal, it should be possible to work around this and use it inside node scripts.

You could run the globally installed `carbon-now` command with something like [`execa`](https://github.com/sindresorhus/execa). This would even work with a local copy of `carbon-now-cli` via `package.json` by running the `cli.js` file, that’s pretty much how [the tests for `carbon-now-cli` do it](https://github.com/mixn/carbon-now-cli/blob/master/test/cli.test.js#L26-L57).

[This example](https://github.com/mixn/carbon-now-cli/issues/5#issuecomment-422065063) from #5 is a nice example of how you could hook the `carbon-now` command into any node script. Hence, it is not exactly used **as** a “node module”, but only **inside** a node module — I think that is what you were aiming to do though. 

I hope that helps. 🙂
