### ISSUE TITLE
Background images (custom/unsplash)

### ISSUE THREAD

**Issue by flxwu** [mixn/carbon-now-cli#38]
Does carbon-now-cli support background images as carbon.now.sh does? 🙂

**Comment by mixn** [comment]
Hey @flxwu, thanks for opening. 🙂

`carbon-now-cli` does not support background images, I actually remember intentionally leaving this out when I started working on this tool.

Personally, I’ve never seen a piece of code from Carbon being shared with a background image and felt the additional work was not worth it. I still feel that way about it, to be honest. 🙃 Plus with presets and `--open`, manually adding a background image here and there isn’t a big overhead imo.

**Comment by flxwu** [comment]
Hey @mixn , thanks for sharing this!

We're building a Twitter bot for the github.com/30-seconds/ projects and would like to use your tool for creating a nice image, but it would be a lot more awesome to have an unsplash background 🙂

**Comment by mixn** [comment]
Thanks for using, really appreciated! I’m a big fan of the 30 seconds project myself. :)

I’ll think about this some time soon. Not the highest priority atm, but I’ll leave it open as a feature-request that I’ll eventually, probably, maybe add sometime. 😄

**Comment by mixn** [comment]
@flxwu Could you provide a/some ideal usage examples for this feature? How would you expect it to work?
