### ISSUE TITLE
Can I set timeout by myself?

### ISSUE THREAD

**Issue by ZYSzys** [mixn/carbon-now-cli#4]
![screen shot 2018-07-10 at 6 43 18 pm](https://user-images.githubusercontent.com/23313266/42505388-300b5846-8471-11e8-970d-71ef8cc3784e.png)
I do can open [carbon](https://carbon.now.sh) on my browser though it show up slowly.
Upset. Can I set a timeout by myself or what should I do next?

**Comment by mixn** [comment]
Hm, not sure where this is coming from to be honest. A quick Google lead me to this [https://github.com/GoogleChrome/puppeteer/issues/1425](https://github.com/GoogleChrome/puppeteer/issues/1425) — are you behind a firewall of some sort?

**Comment by ZYSzys** [comment]
Thanks. It seems that it is indeed module puppeteer's problem.

**Comment by mixn** [comment]
Glad that worked for you and thank you for closing! 😊
