### ISSUE TITLE
Failed do launch chrome!

### ISSUE THREAD

**Issue by gunar** [mixn/carbon-now-cli#43]
![image](https://user-images.githubusercontent.com/7684574/51537139-e031bf00-1e34-11e9-9a8e-ee32fab447d2.png)

**Comment by mixn** [comment]
Hi @gunar, this is likely a problem with Puppeteer and your system. There are several issues filed with the same heading:

https://github.com/GoogleChrome/puppeteer/issues/807
https://github.com/GoogleChrome/puppeteer/issues/3422
https://github.com/GoogleChrome/puppeteer/issues/2924
https://github.com/GoogleChrome/puppeteer/issues/3424

Maybe try [this](https://github.com/GoogleChrome/puppeteer/issues/807#issuecomment-330056692)?

**Comment by gunar** [comment]
Thank you
