### ISSUE TITLE
Pretty cool but does not work well in Windows 10

### ISSUE THREAD

**Issue by tan-wei** [mixn/carbon-now-cli#48]
Thanks for this great plugin for `carbon`. However, there are some problems with my own computer.
1. `carbon-now` always complains those:
```
  √ Processing async_method.rb
  √ Preparing connection
  ↓ Opening in browser [skipped]
  × Fetching beautiful image
    → ENOENT: no such file or directory, rename 'D:\DemoPorojects\async\examples\carbon.png' -> 'D:\DemoPorojects\ a…
    Copying image to clipboard

  Error: Sending code to https://carbon.now.sh went wrong.

  This is mostly due to:

  – Insensical input like `--start 10 --end 2`
  – Carbon being down or taking too long to respond
  – Your internet connection not working or being too slow
```
It seems that we can not set the timeout value by input parameters. So I try to change `headless-visit.js`, set timeout from 2000 to 20000. It doesn't work.
2. Just like #28, if I use switch `-o`, chrome will not be opened then.

Is anything wrong with my env? Thanks!

**Comment by tan-wei** [comment]
After several times try (more than 10 times), `-h` works.

**Comment by mixn** [comment]
That's right @tan-wei. :) See [https://github.com/mixn/carbon-now-cli/issues/9#issuecomment-414801757](this comment for details).
