### ISSUE TITLE
Generate images recursively from a directory

### ISSUE THREAD

**Issue by bluzi** [mixn/carbon-now-cli#5]
Sometimes it is needed to create images from a folder of sources, like an examples folder.
It'll be faster to allow directory path as input, and reuse the same browser session to create images from all the source files in the directory. 

wdyt?

**Comment by mixn** [comment]
Thanks for the feedback, @bluzi. :) 

This was something I had in mind very early on but then let go cause I had the feeling it was too specific. But nice to see, that it apparently isn’t. :)

It definitely makes sense, now that I think of it. Wrote it down as a to-do and will add once there’s time. :)

**Comment by denny64** [comment]
It would be awesome to be able to output your entire codebase in a minified version !

**Comment by molnarmark** [comment]
I was gonna write a package that sits on top of this project that would do exactly this, but the common #9 issue is happening on my end too.

**Comment by guillermosnipe** [comment]
I know that it looks ugly, it's WIP, but you might find this useful.

https://gist.github.com/guillermosnipe/9532fcf779614d1fc00aa018fa075810

**Comment by mixn** [comment]
I’m considering closing this feature request as I’ve only needed this use case twice so far and simply ran

```
cd some-dir/ && find . -maxdepth 1 -type f -exec carbon-now {} \;
```

to achieve it. :)

I think a nice, small package on top does sound kinda interesting though, @molnarmark. Could you provide a possible usage example? Something that just mirrors the flags and pipes them through?

```
carbon-now-dir some-dir --preset twitter --location ~/Desktop // etc.
```

**Comment by molnarmark** [comment]
@mixn Something like that, yes. The package would probably reuse a lot of the helpers from carbon-now-cli (such as preset validation).

I also imagine it would be run by npx most of the time.

**Comment by mixn** [comment]
@molnarmark Do you technically have the time/interest to work on this at the moment? :) Otherwise I’d likely write a tiny, dirty package some time soon.

**Comment by molnarmark** [comment]
@mixn I would if #9 wouldnt still exist for me. :\ (Even running with -h doesnt fix it for some weird reason)

**Comment by mixn** [comment]
@molnarmark What?! 😮 We even [talked about it here](https://github.com/mixn/carbon-now-cli/issues/9#issuecomment-414098877), I was certain it worked for you (as it did for everyone else). Also the issue has been quiet since, so I was **sure**. Feel free to comment over there with your current error. 🤔

**Comment by molnarmark** [comment]
@mixn Started working on it. :)

**Comment by mixn** [comment]
@molnarmark That is awesome and much appreciated. :) Looking forward to it!

**Comment by molnarmark** [comment]
@mixn https://github.com/molnarmark/carbon-now-dir :)

**Comment by mixn** [comment]
@molnarmark Thank you very much for the fast delivery. :) Happy to have found a “middle ground” and to have this functionality, without added bloat. 👏
