### ISSUE TITLE
Line highlighting option

### ISSUE THREAD

**Issue by Relequestual** [mixn/carbon-now-cli#50]
It looks like Carbon supports highligting individual lines: https://github.com/dawnlabs/carbon/issues/824#issuecomment-513311215

Could this be added as a CLI option?

**Comment by mixn** [comment]
As stated by yourself [https://github.com/dawnlabs/carbon/issues/824#issuecomment-513694282](here), adding it shouldn’t be a problem if when it’s configurable via qs.

**Comment by Relequestual** [comment]
Right. I guess the first step is to try and make it part of the query string config... I'll take a look at that in the next few days and then come back!

**Comment by Relequestual** [comment]
https://github.com/carbon-app/carbon/issues/806 has now been resolved and code can have font attributes changed including colour, however it doesn't add to the URL, which I believe is required for this to wrok?

**Comment by AbstractAlao** [comment]
So has this been implemented? How would you construct the command?

**Comment by Pitasi** [comment]
FWIW it's possible to use the `sl` query param like so: https://carbon.now.sh/?sl=3,5

**Comment by mixn** [comment]
As I’m finalizing the huge [`v2` release](https://github.com/mixn/carbon-now-cli/issues/83), I’ve decided to run a small beta of it. 🙂 This feature will ship with the official `v2` release, which can currently be tested via

```
npm i carbon-now-cli@beta -g
```

Running `carbon-now` with `--interactive` will now yield additional questions regarding line highlighting.

<img width="701" alt="Screenshot 2023-05-12 at 15 11 51" src="https://github.com/mixn/carbon-now-cli/assets/672237/2e2afc27-7d13-4746-977c-4a133e42a5f0">

 And it will — as with all other options — lead to another setting inside your preset named `sl`, for `starting line`.

Assuming this code in a file `unfold.js`:

```
// Example from https://carbon.now.sh/
const unfold = (f, seed) => {
  const go = (f, seed, acc) => {
    const res = f(seed)
    return res ? go(f, res[1], acc.concat([res[0]])) : acc
  }
  return go(f, seed, [])
};
```

Running `carbon-now unfold.js` with a preset that has `"sl": "3,4,5,6"` will lead to the expected result. 🙂

![foo](https://github.com/mixn/carbon-now-cli/assets/672237/c365b674-558d-4269-8d58-9f71168d95bb)

Hope that helps. 🙂

Happy testing and using! `v2` will officially drop any day now. 🥳
