### ISSUE TITLE
Bad folder handling on Windows

### ISSUE THREAD

**Issue by popey456963** [mixn/carbon-now-cli#51]
When you run the following command:

    carbon-now -h C:\Users\USER1\AppData\Local\Temp\tmp-21636fth6rhRO9IAw\M3EDyV9G2G.txt -t C:\Users\USER\AppData\Local\Temp\tmp-21636fth6rhRO9IAw\M3EDyV9G2G.txt

It doesn't understand the absolute path:

    Error: ENOENT: no such file or directory, rename 'C:\Users\USER\Documents\Github\femto-apps\web-file-uploader\carbon.png' -> 'C:\Users\USER\Documents\Github\femto-apps\web-file-uploader\C:\Users\USER\AppData\Local\Temp\tmp-21636fth6rhRO9IAw\M3EDyV9G2G.txt.png'

**Comment by prakhargurunani** [comment]
@popey456963 You are importing the file from a directory of a different user `USER1` and saving the image in a sub directory of the user `USER`. Give a clarification on this if it was a typo error.

**Comment by mixn** [comment]
@prakhargurunani @popey456963 Thank you!
