### ISSUE TITLE
Language in config not working

### ISSUE THREAD

**Issue by redaxmedia** [mixn/carbon-now-cli#55]
The language config is not working using:

```
{
	"default":
	{
		"t": "one-dark",
		"l": "sh",
		"bg": "none",
		"wt": "none",
		"wc": true,
		"fm": "Hack",
		"fs": "16px",
		"ln": false,
		"ds": true,
		"dsyoff": "0",
		"dsblur": "0",
		"wa": false,
		"pv": "10px",
		"ph": "10px",
		"si": false,
		"wm": false,
		"es": "1x",
		"type": "svg"
	}
}
```

BTW: Never shorten keys, variables and stuff. You turned that config into a guessing game.

**Comment by mixn** [comment]
@redaxmedia Hi Henry, thanks for opening and showing interest in `carbon-now-cli`— it’s appreciated!

A couple of things…

1. I didn’t shorten keys, but instead took them as they are from the Carbon web app (see the query string when doing anything in the UI). To help with the possible confusion, I even linked the settings in the docs (seen below) and commented things [in the associated file](https://github.com/mixn/carbon-now-cli/blob/master/src/helpers/default-settings.js). 😉

<img width="882" alt="Screenshot 2020-04-09 at 22 08 18" src="https://user-images.githubusercontent.com/672237/78936479-eef2a900-7aae-11ea-8993-ac3477f06f4b.png">

2. Languages detection [happens automatically](https://github.com/mixn/carbon-now-cli/blob/master/src/helpers/default-settings.js#L6-L9) and for `sh` to work, all you need is a file with a [`.sh` extension](https://github.com/mixn/carbon-now-cli/blob/master/src/helpers/language-map.json#L3).

**Example**
![something-15dd6cf432](https://user-images.githubusercontent.com/672237/78937191-4f361a80-7ab0-11ea-933e-10b87e373513.png)

Hope that helps. 🙂

**Comment by redaxmedia** [comment]
I see, thanks for pointing this out.
