### ISSUE TITLE
Fails to launch chromium in mac

### ISSUE THREAD

**Issue by dhinesh-venkat** [mixn/carbon-now-cli#64]
Error: Navigation failed because browser has disconnected!

**Comment by chiptopher** [comment]
I had the same problem. Using the `--headless` flag seems to have solved the problem.

**Comment by mixn** [comment]
@dhinesh-venkat Works with `--headless` as suggested by @chiptopher.

PS: Thanks! @chiptopher :) 👍

**Comment by CleoMenezes** [comment]
> I had the same problem. Using the `--headless` flag seems to have solved the problem.

Thx. That work for me
