### ISSUE TITLE
Option to process directories of files with include/exclude filters

### ISSUE THREAD

**Issue by mahieyin-rahmun** [mixn/carbon-now-cli#65]
I think it could be a great feature to include an option to specify a target directory, and all files in that directory can be processed. There could also be filtering options based on file extensions, file names etc. 

I am willing to work on a PR if this can be included in the tool.

**Comment by mixn** [comment]
Hey @mahieyin-rahmun, thanks for opening. :) 

Can you take a look at https://github.com/mixn/carbon-now-cli/issues/5? I’d assume that’s what you mean?

**Comment by mahieyin-rahmun** [comment]
Ah yes, #5 matches the criteria. I see that it's already done. Thanks.
