### ISSUE TITLE
Transparant background does not save in png when background is "none"

### ISSUE THREAD

**Issue by Relequestual** [mixn/carbon-now-cli#69]
With the background set to "none" as per the example config, and saving as png, I'd expect to get a transparant background.

But alas, I do not.

I get the hashed "this is transparancy" squares, usually shown in other applications.

![false json](https://user-images.githubusercontent.com/731158/133587215-19c69920-82fe-4fe8-ab29-f95b5f628a0a.png)

**Comment by mixn** [comment]
@Relequestual Hey Ben, thanks for opening, and sorry for the late response. Only now getting back to this project. 🙂

I’m almost done with the large [v2 rewrite](https://github.com/mixn/carbon-now-cli/issues/83 ) and have started looking at open issues as part of v2.

I can’t reproduce this issue at all, and it works flawlessly for me. Here is an example link:

https://carbon.now.sh/?bg=none&t=verminal&wt=bw&l=javascript&width=761&ds=false&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=30px&ph=30px&ln=false&fl=1&fm=Anonymous+Pro&fs=18px&lh=133%25&si=false&es=2x&wm=false&code=%252F%252F%2520Example%2520from%2520https%253A%252F%252Fcarbon.now.sh%252F%250Aconst%2520unfold%2520%253D%2520%28f%252C%2520seed%29%2520%253D%253E%2520%257B%250A%2520%2520const%2520go%2520%253D%2520%28f%252C%2520seed%252C%2520acc%29%2520%253D%253E%2520%257B%250A%2520%2520%2520%2520const%2520res%2520%253D%2520f%28seed%29%250A%2520%2520%2520%2520return%2520res%2520%253F%2520go%28f%252C%2520res%255B1%255D%252C%2520acc.concat%28%255Bres%255B0%255D%255D%29%29%2520%253A%2520acc%250A%2520%2520%257D%250A%2520%2520return%2520go%28f%252C%2520seed%252C%2520%255B%255D%29%250A%257D%253B

While the background does appear not to be transparent, once you download the image, you’ll see that it indeed is. 🙂

![carbon (2)](https://user-images.githubusercontent.com/672237/232259996-c28ad7cd-ce6d-4fab-8340-f3c806f84b78.png)

Hope that helps!
