### ISSUE TITLE
Support for older node/npm versions.

### ISSUE THREAD

**Issue by farkaskid** [mixn/carbon-now-cli#7]
![screen shot 2018-07-11 at 8 21 09 am](https://user-images.githubusercontent.com/16179713/42548454-bee028c6-84e4-11e8-9178-ff69332ee6ba.png)

I think the above is due to my outdated node/npm version. I'm not willing to upgrade the node/npm version for some time now due to my involvement in some legacy projects.

Compatibility information should be mentioned in the README. Also, It would be good if you can add support for lower node/npm versions.

**Comment by bluzi** [comment]
Just a tip: You can use a node version manager like [nvm](https://github.com/creationix/nvm) to easily toggle between older and newer versions of Node.

**Comment by mixn** [comment]
@farkaskid Added. :)
