### ISSUE TITLE
Include Original Line Numbers

### ISSUE THREAD

**Issue by AbstractAlao** [mixn/carbon-now-cli#70]
I just want to osay thank you for this. I was able to automate taking screen shots of over 500+ lines of code. The only problem is that the line numbers options won't put the actual line numbers from the file unless you take a full screenshot of the code. When using the start line and end line option is there a way to show the start and stop line number in the screenshot?

**Comment by mixn** [comment]
As I’m finalizing the huge [`v2` release](https://github.com/mixn/carbon-now-cli/issues/83) I’ve decided to run a small beta of it. 🙂 This feature will ship with the official `v2` release, which can currently be tested via

```
npm i carbon-now-cli@beta -g
```

It will respect the `--start` value and set it as the starting line number when line numbers are enabled.

Assuming this code in a file `read-file-async.util.ts `:

```
import { readFile } from 'node:fs/promises';

export default async (
  file: string,
  shouldEncode: boolean = true
): Promise<Buffer | string> =>
  await readFile(file, { encoding: shouldEncode ? 'utf8' : null });
```

Running

```
carbon-now read-file-async.util.ts --start 3
```

will lead to the expected result. 🙂 There is also a new config setting `fl` for `first line` (adapted from Carbon, as all other settings) that can be manually set inside a given preset.

`--start` will always overwrite it though, as expected.

Happy testing and using! `v2` will officially drop any day now.
