### ISSUE TITLE
Image not downloaded correctly

### ISSUE THREAD

**Issue by livissnack** [mixn/carbon-now-cli#9]
Error: Sending code to https://carbon.now.sh went wrong.

  This is mostly due to:

  – Insensical input like `--start 10 --end 2`
  – Carbon being down or taking too long to respond
  – Your internet connection not working or being too slow

**Comment by HarshitKaushik** [comment]
Same issue. Also, I'm sure about two of these possible reasons.

- Not passing any Insensical input
- Internet connection is working and is 120 Mbps.

@mixn Please help to let us try this awesome thing out.

**Comment by mixn** [comment]
Thanks for reporting, @livissnack. :) It’s really hard for me to debug this in any way, since this is the default error. What OS are you both on? @HarshitKaushik I haven’t tested it on Windows yet… should work for macOS and Linux. :)

**Comment by yedhink** [comment]
I also got the same error. tried it in linux. but passing the `-o` flag opens it in browser, and was  able to edit the image from there.
![](https://i.imgur.com/fePsupc.png)

**Comment by mixn** [comment]
@yedhink Where does the full URL of `TROUBLESHOOTING` lead to? Thanks in advance.

**Comment by yedhink** [comment]
@mixn oops didn't see that it has been cut off . here's the full link :- 
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

**Comment by mixn** [comment]
@yedhink Have you tried the Troubleshooting section for Linux machines mentioned here? https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch

@HarshitKaushik Interesting. I’ve only tested it on High Sierra so far, is an upgrade for you possible? Or no chance?

*@all* I’ve added additional error reporting on branch `bug/9`, hopefully this will help narrow down the problem. Please clone the repo, inside it fetch the `bug/9` branch, install the dependencies and run the main script aka. do this:

```
git clone https://github.com/mixn/carbon-now-cli.git
cd carbon-now-cli
git fetch origin bug/9:bug/9
git checkout bug/9
npm install
node cli.js test/test-dummies/_index.html
```

**Comment by Sneezoo** [comment]
same issue here.
Fixed it for me with the help of the link @mixn send before.
Unfortunately a kernel update was not the solution, but a small change in _headless-visit.js_ instead:
```javascript
const browser = await puppeteer.launch({
  headless: false,
  args: ['--no-sandbox', '--disable-setuid-sandbox']
});
```
Fixed the issue, but as stated in the chrome and puppetteer docs this would be a potential security risk!

@mixn I would like to create a PR with a new simple `--disable-sandbox` flag. Ok for you?

**Comment by mixn** [comment]
My good friend and colleague @Sneezoo was so nice to not just test this on his Linux machine, but also fix it. ❤️ Thanks so much, Flotto — super appreciated. 

I’ve reviewed and run your code, looks good to me.

It’d be good if @livissnack @HarshitKaushik @yedhink could do the same and give feedback prior to merging. Please do this

```
git clone https://github.com/mixn/carbon-now-cli.git
cd carbon-now-cli
npm i
node cli.js test/test-dummies/_index.html -S
```

🤞 🤞 🤞

**Comment by HarshitKaushik** [comment]
I tried with the change in headless-visit.js and from bug/9 branch @mixn . Still it seems to be not working with MasOS Sierra Version 10.12.6. 

<img width="719" alt="screen shot 2018-07-16 at 5 56 30 pm" src="https://user-images.githubusercontent.com/7580209/42758795-544e0fcc-8922-11e8-8de5-336129397c9c.png">

**Comment by mixn** [comment]
@HarshitKaushik Could you try it with a different save location on that branch? E.g. `node cli.js test/test-dummies/_index.html -l ~/Desktop`

**Comment by HarshitKaushik** [comment]
@mixn tried and same error. :(

**Comment by mixn** [comment]
@HarshitKaushik Out of curiosity and to see if this is related, pls try this https://github.com/mixn/carbon-now-cli/issues/9#issuecomment-404693397 and report back. Thank you. :)

**Comment by HarshitKaushik** [comment]
@mixn I think I have found the issue.

Additional info:

  Error: ENOENT: no such file or directory, rename '/Users/harshit/Documents/home-workspace/carbon-now-cli/carbon.png' -> '/Users/harshit/Documents/home-workspace/carbon-now-cli/_index-616b5da3db.png'

Additional info:

  Error: ENOENT: no such file or directory, rename '/Users/harshit/Documents/home-workspace/carbon-now-cli/carbon.png' -> '/Users/harshit/Documents/home-workspace/carbon-now-cli/_index-e26146cc4b.png'

In file headless-visit.test.js, defaultDownloadName is expecting carbon.png but we are getting an image name with "_index-" as prefix and then some hash.

<img width="720" alt="screen shot 2018-07-16 at 7 14 37 pm" src="https://user-images.githubusercontent.com/7580209/42761957-a210bd18-892c-11e8-8aca-44f1c380523f.png">

**Comment by mixn** [comment]
@HarshitKaushik The file is first downloaded as `carbon.png` then renamed to `originalfilename-ID.png`. So the renaming fails because the file doesn’t exist, which means the download fails in the first place. Have you tried upgrading to High Sierra to see if the error is still there?

**Comment by HarshitKaushik** [comment]
Hi @mixn , thanks for letting me know. I'll upgrade to High Sierra and update later on this issue. :)

**Comment by mittalyashu** [comment]
Any progress on this issue?

**Comment by mixn** [comment]
@mittalyashu No proper feedback has been given so far and I unfortunately can’t reproduce this. Try [this](https://github.com/mixn/carbon-now-cli/issues/9#issuecomment-404693397) please and report back. :)

**Comment by mixn** [comment]
@mittalyashu This looks very similar to [https://github.com/GoogleChrome/puppeteer/issues/2894](this), the error is the same + it’s on Windows, even though it is 7 — it’s Windows. 😅 Also doesn’t seem to be the same problem as others in this thread were experiencing, since that one seems to be [https://github.com/GoogleChrome/puppeteer/issues/299](this issue).

**Comment by mittalyashu** [comment]
Here's the issue on chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=831887

**Comment by HarshitKaushik** [comment]
@mixn Apology for the delay on the follow-up to this issue. I upgraded up Mac to High Sierra V 10.13.6 and still facing the same issue and the same error.

<img width="720" alt="42761957-a210bd18-892c-11e8-8aca-44f1c380523f" src="https://user-images.githubusercontent.com/7580209/44297641-86135780-a2f2-11e8-90fe-d914a56b7f3f.png">

**Comment by molnarmark** [comment]
@mixn Please see this commit which fixes the image download issue people are having (including me) by using Chromium's screenshot API.

https://github.com/molnarmark/carbon-now-cli/commit/9738aa78a8291da3d213dc8bfc2e782c6527748d

**Comment by mixn** [comment]
@molnarmark Thanks for your input and for playing with this, I appreciate it. :)

I am aware of the screenshot API and have tried using it in the very beginning but abandoned the idea pretty quickly due to the unacceptable image quality it resulted in.

Without screenshot API (`1238 × 578`):

![without-screenshot-api](https://user-images.githubusercontent.com/672237/44302643-af9da480-a32d-11e8-989a-f704dd1ca1fa.png)

Using screenshot API (`589 × 258`):

![with-screenshot-api](https://user-images.githubusercontent.com/672237/44302646-b5938580-a32d-11e8-8641-51454c445506.png)

*But* your comment made me research this further and lead me to [this](https://github.com/GoogleChrome/puppeteer/issues/1329#issuecomment-343088916) and [this](https://github.com/GoogleChrome/puppeteer/issues/571#issuecomment-325404760) and it did work. :) 

With screenshot API + `deviceScaleFactor: 2`:

![increased-devicescalefactor](https://user-images.githubusercontent.com/672237/44302701-d5777900-a32e-11e8-8286-9892eb94ad48.png)

I will research this further, since it would likely mean no `svg` support. But maybe doing a screenshot could be opt-in via a flag, so it would work for everyone supporting only `png`, but using `'Page.setDownloadBehavior'` by default, having support for both `svg` and `png`.

**Comment by molnarmark** [comment]
@mixn Glad to be of help. :) Carbon CLI was a planned project for me, but had no time, so I'm glad I can help. :+1:

**Comment by mixn** [comment]
Ok, here it goes. :) 

The download is performed differently now, when `-h` is used. It’d be **great** if everyone in this thread could try this out. Especially cause I’m on a Retina display and don’t know for sure how `deviceScaleFactor: 2` will behave on non-Retina displays.

Please do this:

```
git clone https://github.com/mixn/carbon-now-cli.git
cd carbon-now-cli
git checkout fix/9
npm i
node cli.js test/test-dummies/_unfold.js -h
```

This should lead to an image being downloaded that has the same quality as without having used `-h`. For me it works and it does look the same:

Regular usage:

![1-regular-usage](https://user-images.githubusercontent.com/672237/44308627-8fb3c280-a3b9-11e8-8fdd-dfd131193367.png)

Usage with `-h`:

![2-usage-with-headless](https://user-images.githubusercontent.com/672237/44308629-96dad080-a3b9-11e8-9204-294dbce6b532.png)

@molnarmark, @mittalyashu, @HarshitKaushik, @yedhink, @livissnack

**Comment by molnarmark** [comment]
@mixn Works totally fine. :smile: Hopefully this gets put into the next branch and I can continue working on my slideshow tool. :+1:

**Comment by mixn** [comment]
@mittalyashu Ups, I forgot to add [this](https://github.com/mixn/carbon-now-cli/commit/cc432784a639a08c57102a84aa5eb0f7a2173ed4). But honestly, that shouldn’t have anything to do with a download failing. But we’ll see — I don’t ever trust Windows. 😄 Pls repeat the steps @mittalyashu or just pull the changes inside your already existing, cloned repo. Thanks.

**Comment by mittalyashu** [comment]
After re-trying few times, and it worked finally.

### Input

![image](https://user-images.githubusercontent.com/29014463/44340911-f9a89680-a4a3-11e8-85e4-1849d9fe7246.png)

### Output

![_unfold-e434ac6ae3](https://user-images.githubusercontent.com/29014463/44340926-0331fe80-a4a4-11e8-8ccb-4e50ba032884.png)

### Additional information

When I use this `node cli.js test/test-dummies/_unfold.js -h` it doesn't open the chromium browser, but if I use it without `-h` when it opens up the browser. Why? 🤔

When the file is written to the disk, it is renamed from `carbon.png` to `{name of the file}-{randonvalue}.png`. Why?

![image](https://user-images.githubusercontent.com/29014463/44341069-7d628300-a4a4-11e8-8be6-18d131a2a39a.png)

**Comment by mixn** [comment]
@mittalyashu Finally! 👏 So glad it worked.

> When I use this `node cli.js test/test-dummies/_unfold.js -h` it doesn't open the chromium browser, but if I use it without -h when it opens up the browser. Why? 🤔

Because `headless: true` doesn’t seem to work with `'Page.setDownloadBehavior'` (the default download behaviour, issue with Puppeteer). Using `-h` downloads the image differently, which works without issues with `headless: true`.

> When the file is written to the disk, it is renamed from `carbon.png` to `{name of the file}-{randonvalue}.png`. Why?

Pretty obvious, I think — to not overwrite already downloaded images. :) Also, this is a preparation for #5 , the images have to have different names.

**Comment by mittalyashu** [comment]
> Because headless: true doesn’t seem to work with 'Page.setDownloadBehavior' (the default download behaviour, issue with Puppeteer). Using -h downloads the image differently, which works without issues with headless: true.
> 
> Pretty obvious, I think — to not overwrite already downloaded images. :) Also, this is a preparation for #5 , the images have to have different names.

👍👍👍👍👍

But what about the image have black line at the left side.

**Comment by mixn** [comment]
@mittalyashu Yeah, I’ve noticed this, too — but only happens when you use the very default, initial settings. Once I went through interactive mode once, it never occurred to me. Run with `-i` once and answer the questions, shouldn’t be there ever after.

**Comment by mixn** [comment]
@mittalyashu It seems to be related to the font used. Doesn’t occur with `Anonymous Pro`, `Dank Mono`, `Inconsolata`, `Iosevka`, `Monoid`, `Ubuntu Mono`. With the rest it does. Seems to be some pixel-issue related to how the font is rendered. 🤷‍♂️

**Comment by mixn** [comment]
@mittalyashu Ok, I just fixed this for me — it works with every font now without the black `1px` line when `-h` is used. 🎉 Please pull the changes on `fix/9` and try again, should without problems. :) 

Using Hack:

![hack](https://user-images.githubusercontent.com/672237/44346159-957ed600-a495-11e8-890b-2fe4ed1741a0.png)

Using Droid Sans Mono:

![droid sans mono](https://user-images.githubusercontent.com/672237/44346180-a4fe1f00-a495-11e8-8f9e-ec7579e5cafe.png)

**Comment by mittalyashu** [comment]
Yup it worked. 🎉🎉🎉

![chrome_2018-08-20_20-27-02](https://user-images.githubusercontent.com/29014463/44348667-b0af0d00-a4b8-11e8-98e9-ec0344cba655.png)

Found another problem 😓

```
$ node cli.js test/test-dummies/_unfold.js -h -i
? Syntax theme: Seti
? Window theme: None
? Font family: Fira Code
? Font size: 16
? Background color: rgba(191,220,238,1)
? Include window controls? Yes
? Include line numbers? No
? Auto adjust width? Yes
? Line height: 133%
? Vertical padding 50
? Horizontal padding 60
? Include drop shadow? Yes
? Drop shadow y-offset 20px
? Drop shadow blur 73
? Make squared image? No
? Add Carbon watermark? No
? Export size 4x
? Export as… png
? Save these settings as a preset? Yes
? Name of the preset? Use kebab-case. carbon
 √ Processing test\test-dummies\_unfold.js
 √ Preparing connection
 ↓ Opening in browser [skipped]
 √ Fetching beautiful image

  Done!

  The file can be found here: C:\Users\YASHU\Desktop\carbon-now-cli/_unfold-c4f2
1ec11b.png �

```

Here's the output with no padding _(vertical or horizontal)_

![image](https://user-images.githubusercontent.com/29014463/44348709-dc31f780-a4b8-11e8-81f3-e7e0b11c688d.png)

**Comment by mixn** [comment]
@mittalyashu Great! 🎉 About time. 😉 

Also, be aware that this thread is originally only for failed downloads, not follow-up stuff. I will merge `fix/9` later on and publish a new version that ships with `-h` and then close this issue. 👍 🎉 

I’ll still address your problem… what you want is a [valid CSS unit](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Values_and_units), so what you’re looking for here is `50px` and `60px`. 😉 It even says so as the default setting in interactive mode, e.g. `0px`. It doesn’t say `0`.

**Comment by mittalyashu** [comment]
> Great! 🎉 About time. 😉

Yeah, finally it working. Now you can close this issue.

**Comment by HarshitKaushik** [comment]
@mixn @mittalyashu Really appreciate the help with investigating and fixing the issue. This thing is working for me now. And feels awesome! 😉

**Comment by mixn** [comment]
As a TL;DR for everyone, who eventually ends up here somehow:

I published `v1.1.0` and as of that version, `carbon-now-cli` ships with a `--headless`/`-h` flag.

This flag avoids [Puppeteer’s experimental `Page.setDownloadBehavior`](https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setDownloadBehavior) feature and uses [`elementHandle.screenshot()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandlescreenshotoptions) instead.

`elementHandle.screenshot()` works across all OS’s, but leads to just `png`s @ `2x` resolutions. I think that’s fine for an edge case though. 🙃

I am very happy to close this big issue thread and want to thank **everyone** who helped and contributed to fixing this — it’s very much appreciated! 🎉

**Comment by mixn** [comment]
As a TL;DR for everyone, who eventually ends up here somehow:

I published `v1.1.0` and as of that version, `carbon-now-cli` ships with a `--headless`/`-h` flag.

This flag avoids [Puppeteer’s experimental `Page.setDownloadBehavior`](https://chromedevtools.github.io/devtools-protocol/tot/Page#method-setDownloadBehavior) feature and uses [`elementHandle.screenshot()`](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#elementhandlescreenshotoptions) instead.

`elementHandle.screenshot()` works across all OS’s, but leads to just `png`s @ `2x` resolutions. I think that’s fine for an edge case though. 🙃

I am very happy to close this big issue thread and want to thank **everyone** who helped and contributed to fixing this — it’s very much appreciated! 🎉

**Comment by molnarmark** [comment]
While the fix was working for me @mixn, I went through an OS switch (Mint -> Elementary), and got a different error message:

```
  ✔ Processing /tmp/unfold.js
  ✔ Preparing connection
  ↓ Opening in browser [skipped]
  ✖ Fetching beautiful image
    → TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubles
…
    Copying image to clipboard

  Error: Sending code to https://carbon.now.sh went wrong.

  This is mostly due to:

  – Insensical input like `--start 10 --end 2`
  – Carbon being down or taking too long to respond
  – Your internet connection not working or being too slow

  Additional info:

  Error: Failed to launch chrome!
[0322/123307.506231:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

```

Adding `--no-sandbox` to the puppeteer.launch call fixed it for me. I'm probably not the only one who will face this issue though.

```javascript
const browser = await puppeteer.launch({
	headless,
	args: ['--no-sandbox']
});
```

**Comment by mixn** [comment]
@molnarmark I _assumed_ this was the case, since I’ve had it happen in another project a few days ago. :) I’ll most likely add a `--disable-sandbox` flag as initially suggested by @Sneezoo [a long time ago](https://github.com/mixn/carbon-now-cli/pull/16).

Or, he can add it if he wants? :) Don’t want to take away from his work… 

I was thinking no shorthand, e.g. only `--disable-sandbox`. Time/interest my man? :) @Sneezoo

One day I will grow up and change OS more often like a real hAxX0r, too… @molnarmark 👑😎

**Comment by amb1s1** [comment]
I'm having the same issue on CentOs7:

```
➜  carbon-now-cli git:(master) ✗ node cli.js test/test-dummies/_unfold.js -h
  ✔ Processing test/test-dummies/_unfold.js
  ✔ Preparing connection
  ↓ Opening in browser [skipped]
  ✖ Fetching beautiful image
    → TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
    Copying image to clipboard

  Error: Sending code to https://carbon.now.sh went wrong.

  This is mostly due to:

  – Insensical input like `--start 10 --end 2`
  – Carbon being down or taking too long to respond
  – Your internet connection not working or being too slow

  Additional info:

  Error: Failed to launch chrome!
/home/gomdavid/carbon-now-cli/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
```

**Comment by amb1s1** [comment]
This fix my issue on my ubuntu box:

```
sudo apt-get install gconf-service libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxss1 libxtst6 libappindicator1 libnss3 libasound2 libatk1.0-0 libc6 ca-certificates fonts-liberation lsb-release xdg-utils wget
```

**Comment by FrancescoSaverioZuppichini** [comment]
Same on Ubuntu 20.04

```
(.venv) (base) ➜  MarkdownToMedium carbon-now main.py
  ✔ Processing main.py
  ✔ Preparing connection
  ↓ Opening in browser [skipped]
  ✖ Fetching beautiful image
    → TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
    Copying image to clipboard

  Error: Sending code to https://carbon.now.sh went wrong.

  This is mostly due to:

  – Insensical input like `--start 10 --end 2`
  – Carbon being down or taking too long to respond
  – Your internet connection not working or being too slow

  Additional info:

  Error: Failed to launch chrome!

(chrome:53491): Gtk-WARNING **: 14:49:16.756: cannot open display: 


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

```
